### ISSUE TITLE
[Feature] Not skipping empty line

### ISSUE THREAD

**Issue by haoadoresorange** [dtolnay/indoc#46]
Hi,

I generate some boilerplate code and use the crate to nicely format it. However, there is no new blank line that is intended to be there and indoc is skipping it.

Can we provide a `raw` mode where everything is preserved, only indenting the text ?

**Comment by dtolnay** [comment]
As far as I can tell, indoc does not skip empty lines.

**Comment by haoadoresorange** [comment]
https://docs.rs/indoc/1.0.3/indoc/#explanation

According to the doc it does.

**Comment by dtolnay** [comment]
That says an empty line doesn't affect how many spaces are removed from the front of nonempty lines. Like if the input string is indented by N spaces but some lines are empty, that doesn't mean you want 0 spaces getting removed, just because the empty line is actually empty i.e. has 0 leading spaces. Any other behavior, such as insisting on spaces in all the empty lines too, would be silly because trailing whitespace is generally maligned and stripped out by many editors.

I am going to close this because as far as I can tell this is already behaving as requested.
