### ISSUE TITLE
Indenting interpolated strings?

### ISSUE THREAD

**Issue by rauschma** [dtolnay/indoc#52]
Example:

```rust
use indoc::{indoc,printdoc};

fn main() {
    let testing = indoc! {"
        def hello():
            print('Hello, world!')
        hello()
    "};
    printdoc! {"
        def hello():
            {testing}
        hello()
    "}
}
```

Actual output:

```text
def hello():
    def hello():
    print('Hello, world!')
hello()

hello()
```

Desired output

```text
def hello():
    def hello():
        print('Hello, world!')
    hello()
hello()
```

In other words:

* It may make sense to trim whitespace at the end (last newline and any spaces or tabs after it).
* If an interpolation is indented by whitespace (=appears at the beginning of a line), I’d like each of its lines to be prefixed by that whitespace.

**Comment by VorfeedCanal** [comment]
This sounds logical, but definitely goes way beyond the scope of `indoc` crate.

Because `indoc` is just a simple whitespace manipulator crate and you expect full-blown template engine crate.

`{testing}` is not handled by `indoc`, but by normal Rust rules which deal with [std::fmt](https://doc.rust-lang.org/std/fmt/), if you want template crate… [there are hundreds of them](https://lib.rs/template-engine).

**Comment by dtolnay** [comment]
I agree. Thank you @VorfeedCanal.
